# Javascript Node CircleCI 2.1 configuration file

# Check https://circleci.com/docs/2.1/language-javascript/ for more details

version: 2.0

orbs:
  aws-cli: circleci/aws-cli@x.y

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - persist_to_workspace:
          root: .
          # Must be relative path from root
          paths:
            - build/*

  deploy:
    docker:
      - image: circleci/python:3.6

    work_directory: /tmp/my-project
    steps:
      - attach_workspace:
          at: /tmp/my-project

      - run:
          name: Install AWS CLI
          command: pip install awscli --user

      - run:
          name: Deploy to S3 if the build is successful
          command: ~/.local/bin/aws s3 sync --acl public-read /tmp/my-project/build/ s3://happyapp2021 --delete

      - run:
          name: Invalidate Cloudfront distribution
          command: ~/.local/bin/aws cloudfront create-invalidation --distribution-id E3VZPXI7N12VAW --paths "/*"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
